FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements-postgres.txt requirements-messaging.txt ./
RUN pip install --no-cache-dir --disable-pip-version-check \
    -r requirements-postgres.txt \
    -r requirements-messaging.txt

COPY . /app
